---
- name: Install celery init script
  copy: src=celeryd dest=/etc/init.d mode=755 owner=root group=root

- name: Install celery config file  
  template: src=celeryd.conf dest=/etc/default/celeryd mode=644
            owner=root group=root

- name: Enable the celery service
  service:
    name: celeryd
    state: started
    enabled: True
  when: not (ansible_distribution == "Ubuntu" and ansible_distribution_major_version >= "16")

- name: Enable the Celery service using systemd
  systemd:
    name: celeryd
    state: started
    enabled: True
    daemon_reload: True
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version >= "16"