---
- name: Install uwsgi aeon-ztp site file
  copy:
    src: uwsgi.aeon-ztp.ini
    dest: /etc/uwsgi/apps-available/aeon-ztp.ini
    mode: 644
    owner: root
    group: root

- name: Install link to aeon-ztp ini file
  file:
    src: /etc/uwsgi/apps-available/aeon-ztp.ini
    dest: /etc/uwsgi/apps-enabled/aeon-ztp.ini
    owner: root
    group: root
    state: link

- name: Install uwsgi init script
  copy:
    src: uwsgi
    dest: /etc/init.d
    mode: 755
    owner: root
    group: root

- name: Copy default ini config
  copy:
    src: default.ini
    dest: /usr/share/uwsgi/conf
    mode: 644
    owner: root
    group: root

- name: Enable the UWSGI service
  service:
    name: uwsgi
    enabled: yes
    state: started