"""empty message

Revision ID: c85bf3b2787f
Revises: 
Create Date: 2018-03-13 10:03:44.026975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c85bf3b2787f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('ip_addr', sa.String(length=16), nullable=False),
    sa.Column('os_name', sa.String(length=16), nullable=False),
    sa.Column('serial_number', sa.String(length=64), nullable=True),
    sa.Column('hw_model', sa.String(length=64), nullable=True),
    sa.Column('os_version', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('message', sa.String(length=10000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('facts', sa.String(length=2000), nullable=True),
    sa.Column('finally_script', sa.String(length=256), nullable=True),
    sa.Column('image_name', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('ip_addr')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('devices')
    # ### end Alembic commands ###
