- name: update hostname
  hostname: name={{ Hostname }}

- name: update hostname in /etc/hosts
  command: sed  -ie 's/^\(127.0[^ \t]*\)[ \t]*ubuntu$/\1\t{{ Hostname }}/g' /etc/hosts
  ignore_errors: true

- name: Update apt
  apt:
    update_cache: yes

- include: users.yml
- include: software.yml
- include: interfaces.yml
