#!/usr/bin/env python

from flask import request, send_from_directory
from ztp_flask import app, manager
import ztp_celery


@app.route('/api/config0/nxos')
def nxos_bootconf():
    return send_from_directory('static', 'nxos-config0.conf')


@app.route('/api/register/nxos', methods=['GET', 'POST'])
def nxos_register():
    from_ipaddr = request.args.get('ip_addr') or request.remote_addr
    ztp_celery.do_this_thing.delay(os_name='nxos', ip_addr=from_ipaddr)
    return "OK"


if '__main__' == __name__:
    manager.run()
