#!/usr/bin/env python

import os
from flask import Flask, send_from_directory
from flask.ext.script import Manager

app = Flask(__name__, static_url_path='')
manager = Manager(app)

@app.route('/api/config0/nxos')
def nxos_bootconf():
    return send_from_directory('static', 'nxos-config0.conf')


if '__main__' == __name__:
    manager.run()