Vagrant.configure(2) do |config|
  config.vm.box = "robwc/minitrusty64"
  config.vm.hostname = 'aeon-ztp'
  config.vm.network "private_network", ip: "192.168.59.254", nic_type: "virtio"

  config.vm.provider "virtualbox" do |vb|
    vb.name = 'aeon-ztp'
    vb.gui = true
    vb.memory = '1024'
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "install-via-ansible.yml"
  end

end
