---
dhcp_cidr: "{{ interfaces['eth1']['address'] }}"
dhcp_subnet: "{{ dhcp_cidr | ipaddr('network') }}"
dhcp_netmask: "{{ dhcp_cidr | ipaddr('netmask') }}"
dhcp_gateway: "{{ interfaces['eth1']['gateway'] }}"
dhcp_address: "{{ dhcp_cidr | ipaddr('address') }}"
dhcp_lease_start: "{{ dhcp_cidr | ipaddr('10') | ipaddr('address')}}"
dhcp_lease_end: "{{ dhcp_cidr | ipaddr('-10') |ipaddr('address') }}"
dhcp_nameserver: "{{ ansible_dns['nameservers'][0] }}"
